### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by chalbersma** [goldmann/wildfly-copr#1]
Is the plan for this to be updated to match wildfy? Is there a good EPEL repository for wildfly?

**Comment by goldmann** [comment]
Whoa,  I totally missed that issue. I'll update this spec tomorrow to build latest wildly package.

There is no EPEL repo with wildfly.

**Comment by chalbersma** [comment]
@goldmann Nice. Thanks man!

**Comment by goldmann** [comment]
I've upgraded copr - could you please check if the 10.0.0.Final version works fine? I don't have now time to test it :(

**Comment by goldmann** [comment]
I just run basic test and it seems it works for me, can you confirm it?

**Comment by rarguello** [comment]
I think you can close this.
