### ISSUE TITLE
COPR "wildfly" group

### ISSUE THREAD

**Issue by rarguello** [goldmann/wildfly-copr#8]
I asked fedora-infrastructure for a new COPR group called "wildfly" so we can use that instead of your personal repo:

https://pagure.io/fedora-infrastructure/issue/7443

Please move the package to that group once it's created.
Thanks!

**Comment by goldmann** [comment]
Great, thank you!

**Comment by rarguello** [comment]
"wildfly" group created:


https://copr.fedorainfracloud.org/groups/g/wildfly/coprs/
